"""
State definitions for the Fiber Maintenance Agent v7.1-Final.

All states use TypedDict with LangGraph Annotated reducers.
Pydantic models enforce structured output via with_structured_output.

Key v7.1 additions:
- NormalizedParams: strong-typed parameters aligned with C++ backend int32/enum
- RuleJudgment: programmatic judgment result (zero LLM)
- AnalysisVerdict: LLM-assisted analysis conclusion
- LoopRecord: enhanced loop audit trail
- MainGraphState: full state with loop control, narrator validation, audit
"""

from __future__ import annotations

import operator
import uuid
from datetime import datetime
from typing import Annotated, Literal, Optional

from langchain_core.messages import BaseMessage, HumanMessage
from langgraph.graph.message import add_messages
from pydantic import BaseModel, Field
from typing_extensions import TypedDict


# =============================================================================
# Strong-Typed Pydantic Models
# =============================================================================


class NormalizedParams(BaseModel):
    """
    Normalized parameters — strictly aligned with C++ backend int32/enum/string.

    This is the output of ParamGate (Layer 2 validation).
    All IDs are positive integers, colors are enum strings, times are ISO 8601.
    """

    fiber_ids: list[int] = Field(default_factory=list, description="Fiber IDs (positive int)")
    board_ids: list[int] = Field(default_factory=list, description="Board IDs (positive int)")
    port_ids: list[int] = Field(default_factory=list, description="Port IDs (positive int)")
    port_refs: list[dict] = Field(default_factory=list, description="[{board_id, port_id}]")
    color: Optional[Literal["RED", "YELLOW", "GREEN"]] = None
    start_time: Optional[str] = Field(default=None, description="ISO 8601 start time")
    end_time: Optional[str] = Field(default=None, description="ISO 8601 end time")
    ne_id: Optional[int] = Field(default=None, description="Network element ID")
    question: Optional[str] = Field(default=None, description="Knowledge QA question text")
    parse_failures: list[str] = Field(default_factory=list, description="Parse error messages")


class RuleJudgment(BaseModel):
    """
    Programmatic judgment result — generated by rule_judgment node, NOT by LLM.

    Contains threshold-based findings that the Narrator must faithfully translate.
    """

    status: Literal["NORMAL", "WARNING", "CRITICAL"] = Field(description="Overall status")
    findings: list[str] = Field(default_factory=list, description="Programmatic findings")
    metrics: dict = Field(default_factory=dict, description="Key metrics for Narrator reference")
    suggested_actions: list[str] = Field(default_factory=list, description="Recommended actions")


class AnalysisVerdict(BaseModel):
    """
    Analysis conclusion — LLM-assisted judgment (structured output from 14b).

    Used by analysis_expert node to decide whether more data is needed.
    """

    conclusion: str = Field(description="One-sentence conclusion")
    severity: Literal["NORMAL", "WARNING", "CRITICAL"] = Field(description="Severity level")
    evidence: list[str] = Field(default_factory=list, description="Supporting data points")
    confidence: float = Field(ge=0, le=1, description="Confidence score 0-1")
    need_more_data: bool = Field(default=False, description="Whether additional data is needed")
    additional_query: Optional[dict] = Field(
        default=None, description='{"reason":"...", "tool":"...", "params":{...}}'
    )


class LoopRecord(BaseModel):
    """
    Enhanced loop audit record [v7.1].

    Records each ReAct loop iteration for audit trail and no-progress detection.
    """

    loop_number: int = Field(description="Loop iteration number")
    reason: str = Field(description="Reason for requesting more data")
    tool_requested: str = Field(description="Tool name requested")
    action_signature: str = Field(description="MD5 hash of action+observation")
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())


class IntentResult(BaseModel):
    """Intent classification result (enforced via with_structured_output on 14b)."""

    intent: Literal[
        "single_query",
        "batch_query",
        "spanloss_analysis",
        "color_diagnosis",
        "trend_analysis",
        "health_check",
        "report_generation",
        "knowledge_qa",
        "chitchat",
    ] = Field(description="Identified user intent")
    fiber_ids: list[str] = Field(default_factory=list, description="Extracted fiber IDs")
    board_ids: list[str] = Field(default_factory=list, description="Extracted board IDs")
    port_ids: list[str] = Field(default_factory=list, description="Extracted port IDs")
    ne_id: Optional[str] = Field(default=None, description="Network element ID")
    color: Optional[str] = Field(default=None, description="Color filter")
    time_range: Optional[str] = Field(default=None, description="Time range expression")
    confidence: float = Field(ge=0, le=1, description="Classification confidence")


# =============================================================================
# Main Graph State [v7.1]
# =============================================================================


class MainGraphState(TypedDict):
    """
    Main orchestration graph state — v7.1-Final.

    Contains all fields needed for:
    - Rule engine + Fast Path
    - Parameter validation + clarification
    - Controlled Loop with four termination safeguards
    - Narrator validation loop [v7.1]
    - Degradation tracking
    - Full audit trail
    """

    # === Conversation ===
    messages: Annotated[list[BaseMessage], add_messages]
    thread_id: str
    user_input: str

    # === Rule Engine ===
    rule_match: Optional[dict]  # RuleMatch serialized
    fast_path_result: Optional[str]  # Fast Path direct output

    # === Intent & Parameters ===
    intent: Optional[str]
    intent_result: Optional[dict]  # IntentResult serialized
    raw_extractions: Optional[dict]
    normalized_params: Optional[dict]  # NormalizedParams serialized

    # === Loop Control (Four Termination Safeguards) ===
    loop_count: int
    max_loops: int  # Default 3
    llm_call_count: int  # Total LLM call count
    max_llm_calls: int  # Default 10
    no_progress_count: int  # No-progress counter
    last_action_signature: Optional[str]
    loop_history: Annotated[list[dict], operator.add]  # LoopRecord list

    # === Data (summaries only, not raw) ===
    collected_data_summary: Optional[str]
    rule_judgment: Optional[dict]  # RuleJudgment serialized
    analysis_verdict: Optional[dict]  # AnalysisVerdict serialized

    # === Narrator Validation [v7.1] ===
    narration: Optional[str]  # Narrator raw output
    narrator_validation_passed: Optional[bool]  # Validation result

    # === Report ===
    report_content: Optional[str]
    report_eval: Optional[dict]  # {"passed": bool, "refinement_count": int}

    # === Batch ===
    batch_chunks: list[dict]
    batch_results: Annotated[list[dict], operator.add]
    batch_progress: dict

    # === Knowledge ===
    rag_context: list[str]

    # === Degradation ===
    degradation_level: int  # 0=normal, 1-4=degraded

    # === Output ===
    final_output: Optional[str]
    processing_path: str  # "fast" / "normal" / "heavy" / "degraded" / "blocked"

    # === Audit ===
    request_id: str
    audit_trail: Annotated[list[dict], operator.add]

    # === Metadata ===
    token_budget_remaining: int
    session_start_time: str

    # === Tracing [v7.1] ===
    trace_id: str  # Unique trace ID for request-level tracking


# =============================================================================
# Sub-graph States
# =============================================================================


class DataCollectorState(TypedDict):
    """Data collector sub-graph state (ReAct Agent + ToolNode)."""

    messages: Annotated[list[BaseMessage], add_messages]
    fiber_ids: list[int]
    query_type: str
    results: dict
    errors: list[str]
    retry_count: int


class BatchChunkState(TypedDict):
    """Single chunk state for Send dispatch unit."""

    chunk_id: str
    fiber_ids: list[int]  # <= 50 per chunk
    chunk_index: int
    result: Optional[dict]
    error: Optional[str]
    idempotency_key: str


class ProactiveState(TypedDict):
    """Proactive diagnosis sub-graph state (event-triggered, no user interaction)."""

    event: dict
    fiber_id: Optional[int]
    collected_data: Optional[str]
    analysis: Optional[str]
    alert_message: Optional[str]
    timeout_exceeded: bool


# =============================================================================
# Default State Factory
# =============================================================================


def create_initial_state(user_message: str, thread_id: str = "") -> dict:
    """
    Create initial state for a new conversation turn.

    Args:
        user_message: The user's input text
        thread_id: Conversation thread ID (auto-generated if empty)

    Returns:
        Complete initial state dict matching MainGraphState schema
    """
    from ..config import MAX_LLM_CALLS, MAX_LOOPS

    # Generate trace_id for request-level tracking
    trace_id = uuid.uuid4().hex[:12]

    return {
        "messages": [HumanMessage(content=user_message)],
        "thread_id": thread_id or uuid.uuid4().hex[:12],
        "user_input": user_message,
        # Rule engine
        "rule_match": None,
        "fast_path_result": None,
        # Intent & params
        "intent": None,
        "intent_result": None,
        "raw_extractions": None,
        "normalized_params": None,
        # Loop control
        "loop_count": 0,
        "max_loops": MAX_LOOPS,
        "llm_call_count": 0,
        "max_llm_calls": MAX_LLM_CALLS,
        "no_progress_count": 0,
        "last_action_signature": None,
        "loop_history": [],
        # Data
        "collected_data_summary": None,
        "rule_judgment": None,
        "analysis_verdict": None,
        # Narrator [v7.1]
        "narration": None,
        "narrator_validation_passed": None,
        # Report
        "report_content": None,
        "report_eval": None,
        # Batch
        "batch_chunks": [],
        "batch_results": [],
        "batch_progress": {},
        # Knowledge
        "rag_context": [],
        # Degradation
        "degradation_level": 0,
        # Output
        "final_output": None,
        "processing_path": "normal",
        # Audit
        "request_id": uuid.uuid4().hex[:16],
        "audit_trail": [],
        # Metadata
        "token_budget_remaining": 10000,
        "session_start_time": datetime.now().isoformat(),
        # Tracing [v7.1]
        "trace_id": trace_id,
    }
